pipeline {
    agent any
    tool {
        Maven "maven3 9.6"
        stages {
            stage ("Git clone") {
                steps {
                    git 'https://github.com/Mkyeboah/maven-web-app.git'
                }
            }
        }
    }
}